### ISSUE TITLE
On what image sizes can Face Shift-net work?

### ISSUE THREAD

**Issue by muxgt** [Zhaoyi-Yan/Shift-Net_pytorch#117]
From non-square sizes it worked for me only on 512x768. On other sizes it gives this:

Traceback (most recent call last):
  File "/content/Shift-Net_pytorch/train.py", line 65, in <module>
    model.optimize_parameters()
  File "/content/Shift-Net_pytorch/models/face_shift_net/face_shiftnet_model.py", line 408, in optimize_parameters
    self.forward()
  File "/content/Shift-Net_pytorch/models/face_shift_net/face_shiftnet_model.py", line 226, in forward
    _, flip_feat = self.netG(self.real_A_flip)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/data_parallel.py", line 153, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/Shift-Net_pytorch/models/modules/shift_unet.py", line 224, in forward
    d3 = self.d3_norm(self.d3_dc(F.relu_(torch.cat([d2, e6], dim=1))))
RuntimeError: Sizes of tensors must match except in dimension 2. Got 13 and 12

Is it the intended behavior? Becauase regular Shift-net works on all image sizes.

**Comment by Zhaoyi-Yan** [comment]
No,  I will fix it in one hour.

**Comment by muxgt** [comment]
Thank you! It's working.
