### ISSUE TITLE
InnerCos Bug using soft_shift

### ISSUE THREAD

**Issue by tchaton** [Zhaoyi-Yan/Shift-Net_pytorch#55]
(epoch: 1, iters: 800, time: 0.027, data: 0.521) G_GAN: 2.870 G_L1: 31.211 D: 0.407 
(epoch: 1, iters: 1600, time: 0.027, data: 0.009) G_GAN: 5.973 G_L1: 25.281 D: 0.072 
(epoch: 1, iters: 2400, time: 0.029, data: 0.010) G_GAN: 6.557 G_L1: 21.723 D: 0.005 
(epoch: 1, iters: 3200, time: 0.029, data: 0.010) G_GAN: 5.861 G_L1: 17.568 D: 0.006 
(epoch: 1, iters: 4000, time: 0.028, data: 0.011) G_GAN: 5.291 G_L1: 16.388 D: 0.061 
(epoch: 1, iters: 4800, time: 0.029, data: 0.014) G_GAN: 5.334 G_L1: 15.123 D: 0.006 
(epoch: 1, iters: 5600, time: 0.028, data: 0.010) G_GAN: 5.188 G_L1: 16.427 D: 0.219 
Traceback (most recent call last):
  File "train.py", line 33, in <module>
    model.set_gt_latent()
  File "/home/tchaton/projects/original/Shift-Net_pytorch/models/shift_net/shiftnet_model.py", line 169, in set_gt_latent
    self.netG(real_B) # input ground truth
  File "/home/tchaton/virtualenvs/labelbox/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/tchaton/virtualenvs/labelbox/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 121, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/tchaton/virtualenvs/labelbox/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/tchaton/projects/original/Shift-Net_pytorch/models/modules/shift_unet.py", line 59, in forward
    return self.model(input)
  File "/home/tchaton/virtualenvs/labelbox/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/tchaton/projects/original/Shift-Net_pytorch/models/modules/unet.py", line 83, in forward
    return self.model(x)
  File "/home/tchaton/virtualenvs/labelbox/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/tchaton/virtualenvs/labelbox/lib/python3.6/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/home/tchaton/virtualenvs/labelbox/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/tchaton/projects/original/Shift-Net_pytorch/models/modules/unet.py", line 85, in forward
    x_latter = self.model(x)
  File "/home/tchaton/virtualenvs/labelbox/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/tchaton/virtualenvs/labelbox/lib/python3.6/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/home/tchaton/virtualenvs/labelbox/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/tchaton/projects/original/Shift-Net_pytorch/models/modules/shift_unet.py", line 134, in forward
    x_latter = self.model(x)
  File "/home/tchaton/virtualenvs/labelbox/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/tchaton/virtualenvs/labelbox/lib/python3.6/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/home/tchaton/virtualenvs/labelbox/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/tchaton/projects/original/Shift-Net_pytorch/models/shift_net/InnerCos.py", line 39, in forward
    self.loss = self.criterion(self.former_in_mask, self.target.expand_as(self.former_in_mask).type_as(self.former_in_mask))
RuntimeError: The expanded size of the tensor (8) must match the existing size (32) at non-singleton dimension 0

The batch_size don't match.

**Comment by Zhaoyi-Yan** [comment]
#56
