### ISSUE TITLE
Pretrained model for face center inpainting is corrupted

### ISSUE THREAD

**Issue by silence1114** [Zhaoyi-Yan/Shift-Net_pytorch#91]
Hi,the uploaded model for face center inpainting(named 30_net_G) is corrupted. Can you upload it again? Thx!

**Comment by Zhaoyi-Yan** [comment]
Could you post the error, it shouldn't be corrupted I think.

**Comment by silence1114** [comment]
I downloaded the model for face center inpainting, it is only 11 Mb in size, while the other three pretained models , ie. face random mask model, paris random mask model and paris center mask model are all 209 Mb.

**Comment by silence1114** [comment]
I tested the face random mask model, paris random mask model and paris center mask model , all got good results. But when I tested the face center mask model, I got an error:

Traceback (most recent call last):
  File "test.py", line 20, in <module>
    model = create_model(opt)
  File "/home/arch/svan/Shift-Net_pytorch-master/Shift-Net_pytorch-master/models/__init__.py", line 30, in create_model
    model.initialize(opt)
  File "/home/arch/svan/Shift-Net_pytorch-master/Shift-Net_pytorch-master/models/shift_net/shiftnet_model.py", line 119, in initialize
    self.load_networks(opt.which_epoch)
  File "/home/arch/svan/Shift-Net_pytorch-master/Shift-Net_pytorch-master/models/shift_net/base_model.py", line 102, in load_networks
    state_dict = torch.load(load_path, map_location=str(self.device))
  File "/usr/lib/python3.7/site-packages/torch/serialization.py", line 387, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/usr/lib/python3.7/site-packages/torch/serialization.py", line 581, in _load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
RuntimeError: unexpected EOF. The file might be corrupted.

**Comment by Zhaoyi-Yan** [comment]
Oh, my God!  The model is wrong! I cannot find the original model and I will retrain the model and will upload the model tomorrow.

**Comment by silence1114** [comment]
> Oh, my God! The model is wrong! I cannot find the original model and I will retrain and upload it tomorrow.

Thank you very much. ^_^

**Comment by Zhaoyi-Yan** [comment]
I have trained the model and upload it, please check.
